### ISSUE TITLE
[FEATURE] State returned in tip service

### ISSUE THREAD

**Issue by sirdeggen** [libsv/pulse#101]
**Request**
Please add `state`, `chainwork`, and `height` to the response in the tips service.

**Describe the solution you'd like**
Here is the same tip response from HeaderSV vs. Pulse to demo the difference.

**Describe alternatives you've considered**
Do not bother adding confirmations - that’s redundant, always 1.

**Additional context**
```bash
root@pulse:~/app# curl https://spv.elas.network/api/v1/chain/tips | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   498    0   498    0     0   1556      0 --:--:-- --:--:-- --:--:--  1561
[
  {
    "header": {
      "hash": "00000000000000000316bf5cc639afed4456802eb857c87aa144de6f618a4a4a",
      "version": 550486016,
      "prevBlockHash": "000000000000000001a8e028c85987b5395cd98acc3c56827ca3c7d4d2ad2382",
      "merkleRoot": "96f05ce9ca175fd5c5990c75d4b6f9ccee71b812d730a0bc67602bfeb91ee80c",
      "creationTimestamp": 1681869322,
      "difficultyTarget": 403467816,
      "nonce": 4124729382,
      "transactionCount": 0,
      "work": 379907749537637900000
    },
    "state": "LONGEST_CHAIN",
    "chainWork": 393050848331486800000000000,
    "height": 788239,
    "confirmations": 1
  }
]
root@pulse:~/app# curl https://pulse.ö.network/api/v1/chain/tips | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   346  100   346    0     0    624      0 --:--:-- --:--:-- --:--:--   632
[
  {
    "hash": "00000000052af1fde60cd53a4f31c1654fffa74ab4f661d51233c70a319dc5ef",
    "version": 1,
    "prevBlockHash": "00000000075f803fbc3597bd1161eca45d21362bcfc5b8c8a82adb3bc5a2ec5f",
    "merkleRoot": "c95d9ed72a4eb53e0ef22cfbabc51839e399be520f080c6c8f665114ac76f4a5",
    "creationTimestamp": 1278790772,
    "difficultyTarget": 0,
    "nonce": 257266445,
    "work": 1299755011662333
  }
]
root@pulse:~/app#
```

**Comment by sirdeggen** [comment]
@proapi I started working on this issue because it’s hard to explain - would be great if I could ask the team to take it from here: https://github.com/libsv/pulse/pull/100

You don’t have to use my work, but that’s the idea roughly. Easier to do in code than explain.

**Comment by proapi** [comment]
@sirdeggen yes, we will take it from there, thanks!

**Comment by pawellewandowski98** [comment]
@sirdeggen I created new PR, you can check if everything is as you expect. Now the response looks like this:
` 
 {
    "header": {
      "hash": "000000000000000000067df310431662105f398503be9ba6220566826de626d9",
      "version": 591101952,
      "prevBlockHash": "0000000000000000012bd28cd061daf096ed90103f198a6d574592198beaeaf1",
      "merkleRoot": "acc7754ca5dfa5d4b65252b3ee608d904462928e4ff0b54ce53a4e03156760d1",
      "creationTimestamp": 1681909102,
      "difficultyTarget": 0,
      "nonce": 4230574886,
      "work": 427666320953686909218
    },
    "state": "LONGEST_CHAIN",
    "chainWork": 393080801991375037515155603,
    "height": 788313
  }
]
`
