### ISSUE TITLE
[BUG] Hex string format

### ISSUE THREAD

**Issue by sirdeggen** [libsv/pulse#81]
The format of the response is imperfect, a few hex values are being returned as Uint arrays.

**To Reproduce**
1. Spin her up and await at least the first blockheader.
2. GET first blockheader state [example](http://localhost:8080/api/v1/chain/header/state/000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f)
3. Notice the value "hash", "merkleroot" and "prevblockhash" are arrays.

**Expected behavior**
The value of "hash" should be a hex string like [here](https://spv.elas.network/api/v1/chain/header/state/000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f): 

**Screenshots & Logs**
Example incorrect:
```json
{
  "header": {
    "hash": [111,226,140,10,182,241,179,114...],
    "version": 1,
    "merkleRoot": [59,163,237,253,122...],
    "creationTimestamp": "2009-01-03T18:15:05Z",
    "nonce": 2083236893,
    "work": 0,
    "prevBlockHash": [0,0,0,0,0...],
    "difficultyTarget": 0
  },
  "state": "LONGEST_CHAIN",
  "chainWork": 0,
  "height": 0,
  "confirmations": 0
}
```

Example correct

```json
{
  "header": {
    "hash": "000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f",
    "version": 1,
    "prevBlockHash": "0000000000000000000000000000000000000000000000000000000000000000",
    "merkleRoot": "4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b",
    "creationTimestamp": 1231006505,
    "difficultyTarget": 486604799,
    "nonce": 2083236893,
    "work": 4295032833
  },
  "state": "LONGEST_CHAIN",
  "chainWork": 4295032833,
  "height": 0,
  "confirmations": 785304
}
```

**System Information (please complete the following information):**
Docker MacOS latest, Intel

**Comment by sirdeggen** [comment]
In hindsight there are a few details of the response which do not exactly match, like timestamp for example.

**Comment by sirdeggen** [comment]
`creationTimestamp` ought to be Unix epoch time int
`confirmations` ought to be removed

**Comment by sirdeggen** [comment]
`work` value is missing. This needs to be calculated based on the difficultyTarget.

```
difficulty = difficulty_1_target / current_target
```
https://wiki.bitcoinsv.io/index.php/Difficulty

**Comment by pawellewandowski98** [comment]
Thanks! already created PR with changes connected to this issue but I still have some questions:
- Are you sure that confirmations should be removed? I fixed them so now endpoints returns correct number but If you want I can remove it
- How can I get or calculate difficulty target? because for now endpoints always returns 0 in this field

**Comment by sirdeggen** [comment]
@pawellewandowski98 sorry for my slow reply - I'll get the calculation to you for difficulty, I have to look it up. It's a comparison between the target value now and the target value of the genesis block, I think.

Just leave confirmations in just now. I wanted to save you some  work because I don't know the use case. Confirmations is  an old term used when considering whether or not to trust a transaction's immutability. This  is not needed in BSV as it has the first seen rule, essentially. So a useless number to report I suspect.

**Comment by sirdeggen** [comment]
Hex issues fixed in https://github.com/libsv/pulse/pull/88
